development:
  yelp_key: "NhddQRDNcF1ul0wnKMH4vfElRMW3Ype3NjAOAvBwbK6K7NYxPzOPqnGPy_4SC2m0OtFqLzwF5FefK0MDYkPaq3-YHzeGg5lA0N1594-_E7sFhwxZFfxGPstLar5UW3Yx"

  google_api_key: '1076400101623-ipfra6imhplocvueb6kn9fru8amlf11b.apps.googleusercontent.com'
  google_secret_key: 'fhkF2M_mKxIvHPCy0psnJhlY'
